---
- name: Re-set cron job for certbot renewal.
  cron:
    name: Certbot automatic renewal.
    job: "scl enable pytyon27 \"{{ certbot_script }} renew --quiet --no-self-upgrade\""
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
